included:
  - Onban
disabled_rules:
  - todo

indentation_width:
  indentation_width: 4

force_unwrapping:
  severity: error

# https://github.com/codesquad-members-2023/swift-onban-05/wiki/%F0%9F%91%8B-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C#7-10-200-rule%EC%9D%84-%EC%A0%81%EC%9A%A9%ED%95%9C%EB%8B%A4
function_body_length:
  - 10 # warning
  - 20 # error

type_body_length:
  - 200 # warning
  - 400 # error

opt_in_rules:
  # https://github.com/codesquad-members-2023/swift-onban-05/wiki/%F0%9F%91%8B-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C#2-%EA%B0%95%EC%A0%9C-%EC%96%B8%EB%9E%98%ED%95%91-%EC%82%AC%EC%9A%A9%EC%9D%84-%EC%A7%80%EC%96%91%ED%95%9C%EB%8B%A4
  - force_unwrapping 
  - indentation_width
  # https://github.com/codesquad-members-2023/swift-onban-05/wiki/%F0%9F%91%8B-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C#6-import-%EB%8A%94-%EC%B5%9C%EC%86%8C%ED%99%94%ED%95%9C%EB%8B%A4
  - sorted_imports
  # https://github.com/codesquad-members-2023/swift-onban-05/wiki/%F0%9F%91%8B-%EC%BD%94%EB%93%9C-%EC%8A%A4%ED%83%80%EC%9D%BC-%EA%B0%80%EC%9D%B4%EB%93%9C#8-%EB%A9%94%EC%84%9C%EB%93%9C-%ED%98%B8%EC%B6%9C-%EC%8B%9C-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0%EA%B0%80-4%EA%B0%9C-%EC%9D%B4%EC%83%81%EC%9D%B4%EB%9D%BC%EB%A9%B4-%EB%9D%BC%EC%9D%B8%EC%9D%84-%EA%B5%AC%EB%B6%84%ED%95%B4%EC%84%9C-%EC%93%B4%EB%8B%A4
  - multiline_arguments
  - multiline_parameters_brackets
