platform :ios, '16.0'
inhibit_all_warnings!

target 'Onban' do
  use_frameworks!
  pod 'SwiftLint'
  pod 'Toaster'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end